const tableData = [
  {
      icon: '/images/users/avatar-1.jpg',
      name: 'Lucinda Stickley', 
      status:'Intrested',visited_at:'2020-09-08 09:30 pm',
      id:1,
      action:true,
    }, 
    {
        icon: '/images/users/avatar-1.jpg',
        name: 'Lucinda Stickley', 
        status:'Intrested',visited_at:'2020-09-08 09:30 pm',
        id:1,
        action:true,
      }, 
  {
      icon: '/images/users/avatar-1.jpg',
      name: 'Lucinda Stickley', 
      status:'Not-Intrested',visited_at:'2020-09-08 09:30 pm',
      id:1,
      action:true,
    }, 
  {
      icon: '/images/users/avatar-1.jpg',
      name: 'Lucinda Stickley', 
      status:'Intrested',visited_at:'2020-09-08 09:30 pm',
      id:1,
      action:true,
    }, 
  {
      icon: '/images/users/avatar-1.jpg',
      name: 'Lucinda Stickley', 
      status:'Not-Intrested',visited_at:'2020-09-08 09:30 pm',
      id:1,
      action:true,
    }, 
  {
      icon: '/images/users/avatar-1.jpg',
      name: 'Lucinda Stickley', 
      status:'Intrested',visited_at:'2021-02-08 09:30 pm',
      id:1,
      action:true,
    }, 
  {
      icon: '/images/users/avatar-1.jpg',
      name: 'Lucinda Stickley', 
      status:'Intrested',visited_at:'2021-09-08 09:30 pm',
      id:1,
      action:true,
    }, 
  {
      icon: '/images/users/avatar-1.jpg',
      name: 'Lucinda Stickley', 
      status:'Intrested',visited_at:'2021-09-08 09:30 pm',
      id:1,
      action:true,
    }, 
  {
      icon: '/images/users/avatar-1.jpg',
      name: 'Lucinda Stickley', 
      status:'Intrested',visited_at:'2020-02-08 10:30 pm',
      id:1,
      action:true,
    }, 
    {
        icon: '/images/users/avatar-1.jpg',
        name: 'Lucinda Stickley', 
        status:'Not-Intrested',
        id:2,
        visited_at:'2019-02-08 11:30 pm',
        action : true,
      },  
];

export { tableData };
